services:
  - type: web
    name: Minigame
    env: docker
    repo: https://github.com/твій-юзернейм/твій-репозиторій
    region: oregon
    plan: free
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/Minigame.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: PORT
        value: 10000 
